### ISSUE TITLE
facebook login success but app not starting

### ISSUE THREAD

**Issue by shamilb** [comphead/ionic#1]
error in console after facebook login
FirebaseError {code: "app/duplicate-app", message: "Firebase: Firebase App named '[DEFAULT]' already exists (app/duplicate-app).", name: "[DEFAULT]", __zone_symbol__currentTask: e, stack: "[DEFAULT]: Firebase: Firebase App named '[DEFAULT]…k (http://localhost:8000/build/vendor.js:5076:33)"}

**Comment by comphead** [comment]
please try with commit #e00feed7a241772250919f7682ba6455c6614bd2
